name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/astral-sh/uv:0.12.23-python3.9-alpine@sha256:8af355c642a711d4b7ca0f53798ecb236345c7496b3f7b234aa4238c329605c3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      
      - name: Cache uv
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: /root/.cache/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      
      - name: Show versions
        run: |
          python --version
          pip --version
          uv --version
      
      - name: Install dependencies
        run: uv sync --frozen --no-cache
      
      - name: Run ruff check
        run: uv run ruff check
      
      - name: Run ruff format check
        run: uv run ruff format --check
      
      - name: Cleanup cache
        if: always()
        run: uv cache prune --ci

