name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/astral-sh/uv:0.11.24-python3.9-alpine@sha256:74f790a258c5ca972409de3b4be99fa03102248c9fc7035d2e641bb044a2e0bb
    
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      
      - name: Cache uv
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: /root/.cache/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      
      - name: Show versions
        run: |
          python --version
          pip --version
          uv --version
      
      - name: Install dependencies
        run: uv sync --frozen --no-cache
      
      - name: Run ruff check
        run: uv run ruff check
      
      - name: Run ruff format check
        run: uv run ruff format --check
      
      - name: Cleanup cache
        if: always()
        run: uv cache prune --ci

