name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/astral-sh/uv:0.9.10-python3.9-alpine@sha256:ea9b07aa69d7a86e09ac34563ad6f291955f6a7fcfa3d740f89c6ce44cec60b9
    
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      
      - name: Cache uv
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: /root/.cache/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      
      - name: Show versions
        run: |
          python --version
          pip --version
          uv --version
      
      - name: Install dependencies
        run: uv sync --frozen --no-cache
      
      - name: Run ruff check
        run: uv run ruff check
      
      - name: Run ruff format check
        run: uv run ruff format --check
      
      - name: Cleanup cache
        if: always()
        run: uv cache prune --ci

